---
version: '2'
services:
  web:
    restart: 'no'
    build:
      context: ./
      #args:
      #  _VER: ${_VER}
    image: ${DOCKER_ID}/${NAME}:${APTLY_VER}
    #command: /bin/sh
    # ports:
    # - 8080:8080
    # - 8081:8081
    # volumes:
    # - "./data:/aptly-data:rw"
